visible_hostname forensics-proxy
http_port 3128
acl allowed_domains dstdomain "/etc/squid/allowed-domains.acl"
acl CONNECT method CONNECT
acl SSL_ports port 443
acl Safe_ports port 80 443

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow allowed_domains
http_access allow CONNECT allowed_domains
http_access deny all

cache deny all
access_log daemon:/var/log/squid/access.log
cache_log /dev/null
